/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"
#include "library/client/utils.h"


void oauth_prog_1(char *host, InputClient *inputClients, int nrInputs){

	CLIENT *clnt;

	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	ClientCredentials *clients = calloc(MAX_CLIENTS_ACCEPTED, sizeof(ClientCredentials));

	for(int i=0; i<nrInputs; i++){

		InputClient input = inputClients[i];

		RequestAuthToken request;
		char *idClient = input.id;
		request.idClient = idClient;
		request.isAutoRefreshActivated = (input.arguments[0] == '1');

		if(strcmp(input.command, "REQUEST") == 0){
			printf("|%s|\n", input.id);
			ResponseAuthToken  *response_auth_token = request_auth_token_1(&request, clnt);

			if(strcmp(response_auth_token->header, "USER_NOT_FOUND") == 0){
				// TO DO
				printf("|%s|\n\n", response_auth_token->header);
				continue;
			}

			// printf("|%s|\n", response_auth_token->auth_token);
			ResponseSignedToken  *response_signed_token = request_signed_token_1(&response_auth_token->auth_token, clnt);
			// printf("|%s|\n\n", response_signed_token->signed_token);

			if(strcmp(response_signed_token->header, "REQUEST_DENIED") == 0){
				// TO DO
				printf("|%s|\n\n", response_signed_token->header);
				continue;
			}

			ResponseBearerToken  *response_bearer_token = request_bearer_token_1(&response_signed_token->signed_token, clnt);
			printf("|%s|\n", response_bearer_token->access_token);
			printf("|%s|\n\n", response_bearer_token->refresh_token);

			addClientCredentials(idClient, 
									response_bearer_token->access_token,
									response_bearer_token->refresh_token, 
									response_bearer_token->ttl, 
									&clients);
			
		} else {
			
			ClientCredentials *credentials = getClientCredentials(idClient, clients);

			if(credentials->ttl <= 0 && strlen(credentials->refresh_token) > 0){
				char *old_refresh_token = credentials->refresh_token;
				ResponseBearerToken  *response_bearer_token = request_new_bearer_token_1(&old_refresh_token, clnt);

				addClientCredentials(idClient, 
									response_bearer_token->access_token,
									response_bearer_token->refresh_token, 
									response_bearer_token->ttl, 
									&clients);
			}
			
			printf("|%s|\n", credentials->id);
			printf("|%s|\n", credentials->access_token);
			printf("|%s|\n", credentials->refresh_token);
			printf("|%d|\n", credentials->ttl);
			printf("|%s|\n", input.command);

			ExecuteDatabaseAction execute_databese_action;
			execute_databese_action.access_token = credentials->access_token;
			execute_databese_action.action = input.command;
			execute_databese_action.file = input.arguments;
			ResponseDatabaseAction *response_databese_action = execute_databasa_action_1(&execute_databese_action, clnt);
			credentials->ttl--;

			printf("|%s|\n\n", response_databese_action->header);
		}

	}

	// printf("{{{{%s}}}}\n", clients[0].id);
	// printf("{{{{%s}}}}\n", clients[1].id);
	// printf("{{{{%s}}}}\n", clients[2].id);

	clnt_destroy (clnt);

}


int main (int argc, char *argv[])
{
	if (argc < 3) {
		printf ("Client need host and input file as arguments!!");
		exit (1);
	}
	
	char* host = argv[1];
	char* file = argv[2];

	InputClient* inputClients;
	int nrInputs = readInputClientFile(file, &inputClients);
	
	oauth_prog_1 (host, inputClients, nrInputs);

	exit (0);
}
