/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "library/server/utils.h"


#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
oauth_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		RequestAuthToken request_auth_token_1_arg;
		char *request_signed_token_1_arg;
		char *request_bearer_token_1_arg;
		char *request_new_bearer_token_1_arg;
		ExecuteDatabaseAction execute_databasa_action_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTH_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_RequestAuthToken;
		_xdr_result = (xdrproc_t) xdr_ResponseAuthToken;
		local = (char *(*)(char *, struct svc_req *)) request_auth_token_1_svc;
		break;

	case REQUEST_SIGNED_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ResponseSignedToken;
		local = (char *(*)(char *, struct svc_req *)) request_signed_token_1_svc;
		break;

	case REQUEST_BEARER_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ResponseBearerToken;
		local = (char *(*)(char *, struct svc_req *)) request_bearer_token_1_svc;
		break;

	case REQUEST_NEW_BEARER_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_ResponseBearerToken;
		local = (char *(*)(char *, struct svc_req *)) request_new_bearer_token_1_svc;
		break;

	case EXECUTE_DATABASA_ACTION:
		_xdr_argument = (xdrproc_t) xdr_ExecuteDatabaseAction;
		_xdr_result = (xdrproc_t) xdr_ResponseDatabaseAction;
		local = (char *(*)(char *, struct svc_req *)) execute_databasa_action_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OAUTH_PROG, OAUTH_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH_PROG, OAUTH_VERS, oauth_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH_PROG, OAUTH_VERS, tcp).");
		exit(1);
	}

	// ---------------------------------

	readUsersAllowed("userIDs.db");
	readPermissionsFile("approvals.db");
	readResourceFiles("resources.db");
	generateSecretKey();

	// ---------------------------------
	
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
