/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "oauth.h"
#include "library/utils.h"

void
oauth_prog_1(char *host)
{
	CLIENT *clnt;
	response  *result_1;
	char * request_auth_token_1_arg = malloc;

	clnt = clnt_create (host, OAUTH_PROG, OAUTH_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_1 = request_auth_token_1(&request_auth_token_1_arg, clnt);

	printf("%s\n", result_1->token);

	if (result_1 == (response *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	clnt_destroy (clnt);
}


int main (int argc, char *argv[])
{

	if (argc < 3) {
		printf ("Client need host and input file as arguments!!");
		exit (1);
	}
	
	char* host = argv[1];
	char* file = argv[2];

	InputClient* inputClients;
	int nrInputs = readInputClientFile(file, &inputClients);

	for(int i=0; i<nrInputs; i++){

		InputClient input = inputClients[i];

		if(strchr(input.command, "REQUEST") == 0){
			oauth_prog_1 (host);
		}

		// if(strchr(input.command, "READ") == 0){
		// 	oauth_prog_1 (host);
		// }

		// if(strchr(input.command, "MODIFY") == 0){
		// 	oauth_prog_1 (host);
		// }

		// if(strchr(input.command, "INSERT") == 0){
		// 	oauth_prog_1 (host);
		// }

		// if(strchr(input.command, "EXECUTE") == 0){
		// 	oauth_prog_1 (host);
		// }

		// if(strchr(input.command, "DELETE") == 0){
		// 	oauth_prog_1 (host);
		// }

	}

exit (0);
}
